# NumPy Foundations for ML

## Objective
Learn and document the essential NumPy operations for machine learning:
- Array creation
- Indexing & slicing
- Arithmetic operations
- Basic statistics

## Why this matters
NumPy is the backbone of ML computation:
- Data preprocessing
- Vectorized operations
- Feeding data to ML models efficiently

## Key Notes
- `.shape` shows dimensions
- `.dtype` shows data type
- `.size` shows number of elements
- `.ndim` shows number of axes

In [1]:
import numpy as np

# Create arrays
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)      # start, stop, step
c = np.zeros((2, 3))         # 2x3 zeros
d = np.ones((3, 2))          # 3x2 ones
e = np.random.randn(3, 3)    # 3x3 random normal numbers

print("a:", a)
print("b:", b)
print("c:\n", c)
print("d:\n", d)
print("e:\n", e)


a: [1 2 3 4 5]
b: [0 2 4 6 8]
c:
 [[0. 0. 0.]
 [0. 0. 0.]]
d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
e:
 [[-0.93166512  0.21403408 -0.64829264]
 [-0.11705713 -0.90185186 -0.89307838]
 [ 1.44950657 -0.58608246  0.40622685]]


In [2]:
print("Shape of e:", e.shape)
print("Data type of e:", e.dtype)
print("Number of elements in e:", e.size)
print("Number of dimensions of e:", e.ndim)


Shape of e: (3, 3)
Data type of e: float64
Number of elements in e: 9
Number of dimensions of e: 2


In [3]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

# Indexing
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing
print("First three elements:", arr[:3])
print("Last two elements:", arr[-2:])

# Boolean indexing
print("Elements > 25:", arr[arr > 25])

Original array: [10 20 30 40 50]
First element: 10
Last element: 50
First three elements: [10 20 30]
Last two elements: [40 50]
Elements > 25: [30 40 50]


In [4]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

# Elementwise operations
print("x + y =", x + y)
print("x * 2 =", x * 2)
print("y / x =", y / x)

# Statistics
print("Mean of x:", x.mean())
print("Sum of y:", y.sum())
print("Standard deviation of x:", x.std())

x + y = [11 22 33 44 55]
x * 2 = [ 2  4  6  8 10]
y / x = [10. 10. 10. 10. 10.]
Mean of x: 3.0
Sum of y: 150
Standard deviation of x: 1.4142135623730951
